import = ["/home/kenneth/.config/alacritty/themes/catppuccin_mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.normal]
family = "Noto Sans Mono"

[window]
opacity = 0.8

[window.padding]
x = 5
y = 10
